### ISSUE TITLE
Missing descriptions for complex input type fields

### ISSUE THREAD

**Issue by ikari-pl** [2fd/graphdoc#24]
When custom input types are defined (an `OperationInput` that is a `GraphQLInputObjectType`), the descriptions of the subfields are not available in the generated docs.

This is a little frustrating to get to even in the GraphiQL, but impossible in graphdoc.

An example, from https://2fd.github.io/graphdoc/github/addprojectcardinput.doc.html . In GraphiQL, I have to go to `AddProjectCardInput` and then click on `projectColumnId` to see its description. In `graphdoc` I can't see this description available anywhere. Frankly, I would like to have it documented already on the level shown at the screenshot, without the extra click.

(Left: github's GraphiQL, right - graphdoc demo)

![image](https://cloud.githubusercontent.com/assets/811702/24156772/cdabdf12-0e57-11e7-8b5d-c34ced97e5ef.png)

**Comment by 2fd** [comment]
Resolved in [v2.2.1](https://github.com/2fd/graphdoc/releases/tag/v2.2.1)  :+1: 

Example: https://2fd.github.io/graphdoc/github/addprojectcardinput.doc.html

**Comment by ikari-pl** [comment]
Wow, you're blazingly fast!
