### ISSUE TITLE
[Audit] Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by benjamingb** [2fd/graphdoc#68]
┌───────────────────────────────────────────────────────
│ Moderate:       Regular Expression Denial of Service        
├───────────────────────────────────────────────────────
│ Package :       marked                                      
├───────────────────────────────────────────────────────
│ Patched in:     >=0.6.2                                     
├───────────────────────────────────────────────────────
│ Dependency of:  @2fd/graphdoc [dev]                         
├───────────────────────────────────────────────────────
│ Path:           @2fd/graphdoc > marked                      
├───────────────────────────────────────────────────────
│ More info :     https://npmjs.com/advisories/812            
└───────────────────────────────────────────────────────

Angular CLI: 7.3.8
Node: 10.15.3
OS: linux x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-ng-packagr   0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         5.1.0
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0

**Comment by dbrudner** [comment]
I might be missing something, but wouldn't this be solved by updating marked to its most recent version?
